# Generated by Django 4.0.7 on 2024-07-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_created_at_remove_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='updated_at',
        ),
    ]
